# Anomalous Financial Transaction Detection

본 대회의 과제는 금융 거래 데이터에서 **이상 거래를 탐지하는 기능**을 개선하고 활용도를 높이는 분류 AI모델을 개발하는 것입니다. 

특히, 클래스 불균형 문제를 해결하기 위해 오픈소스 생성형 AI 모델을 활용하여 부족한 클래스의 데이터를 보완하고, 이를 통해 분류 모델의 성능을 향상시키는 것이 핵심 목표입니다. 

이러한 접근을 통해 금융보안에 특화된 데이터 분석 및 활용 역량을 강화하여 전문 인력을 양성하고, 금융권의 AI 활용 어려움에 따른 해결 방안을 함께 모색하며 금융 산업의 AI 활용 활성화를 지원하는 것을 목표로 합니다.

# Import Library

In [1]:
!pip install sdv

Collecting sdv
  Using cached sdv-1.20.0-py3-none-any.whl.metadata (14 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Using cached boto3-1.38.4-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Using cached botocore-1.38.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (3.1.1)
Collecting graphviz>=0.13.2 (from sdv)
  Using cached graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.24.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (2.1.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (2.2.3)
Requirement already satisfied: tqdm>=4.29 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.67.1)
Collecting copulas>=0.12.1 (from sdv)
  Using cached copulas-0.12.2-py3-none-any.whl.metadata (9.4 kB)
Collecting ctgan>=0.11.0 (from sdv)
  Using cached ctgan-0.11.0-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Using cached deepecho-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting rdt>=1.16.0 (from sdv)
  Using cached rdt-1.16.0-py3-none-any.whl.metadata (10 kB)
Collecting sdmetrics>=0.20.1 (from sdv)
  Using cached sdmetrics-0.20.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: platformdirs>=4.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from sdv) (4.3.7)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (6.0.2)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.13.0,>=0.12.0 (from boto3<2.0.0,>=1.28->sdv)
  Using cached s3transfer-0.12.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.4.0)
Collecting plotly>=5.10.0 (from copulas>=0.12.1->sdv)
  Using cached plotly-6.0.1-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: scipy>=1.9.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (1.15.2)
Collecting torch>=2.0.0 (from ctgan>=0.11.0->sdv)
  Using cached torch-2.7.0-cp311-cp311-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.5.0->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.5.0->sdv) (2025.2)
Requirement already satisfied: scikit-learn>=1.1.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.16.0->sdv) (1.6.1)
Collecting Faker>=17 (from rdt>=1.16.0->sdv)
  Using cached faker-37.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Collecting narwhals>=1.15.1 (from plotly>=5.10.0->copulas>=0.12.1->sdv)
  Using cached narwhals-1.37.0-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python311\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.16.0->sdv) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.16.0->sdv) (3.6.0)
Collecting filelock (from torch>=2.0.0->ctgan>=0.11.0->sdv)
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (4.13.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (1.14.0)
Requirement already satisfied: networkx in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.1.6)
Requirement already satisfied: fsspec in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.0->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.0->sdv) (3.0.2)
Using cached sdv-1.20.0-py3-none-any.whl (157 kB)
Using cached boto3-1.38.4-py3-none-any.whl (139 kB)
Using cached botocore-1.38.4-py3-none-any.whl (13.5 MB)
Using cached copulas-0.12.2-py3-none-any.whl (52 kB)
Using cached ctgan-0.11.0-py3-none-any.whl (24 kB)
Using cached deepecho-0.7.0-py3-none-any.whl (27 kB)
Using cached graphviz-0.20.3-py3-none-any.whl (47 kB)
Using cached rdt-1.16.0-py3-none-any.whl (69 kB)
Using cached sdmetrics-0.20.1-py3-none-any.whl (193 kB)
Using cached faker-37.1.0-py3-none-any.whl (1.9 MB)
Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Using cached plotly-6.0.1-py3-none-any.whl (14.8 MB)
Using cached s3transfer-0.12.0-py3-none-any.whl (84 kB)
Using cached torch-2.7.0-cp311-cp311-win_amd64.whl (212.5 MB)
Using cached narwhals-1.37.0-py3-none-any.whl (331 kB)
Using cached filelock-3.18.0-py3-none-any.whl (16 kB)
Installing collected packages: narwhals, jmespath, graphviz, filelock, Faker, torch, plotly, botocore, s3transfer, rdt, deepecho, copulas, sdmetrics, ctgan, boto3, sdv
Successfully installed Faker-37.1.0 boto3-1.38.4 botocore-1.38.4 copulas-0.12.2 ctgan-0.11.0 deepecho-0.7.0 filelock-3.18.0 graphviz-0.20.3 jmespath-1.0.1 narwhals-1.37.0 plotly-6.0.1 rdt-1.16.0 s3transfer-0.12.0 sdmetrics-0.20.1 sdv-1.20.0 torch-2.7.0

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# 제출 파일 생성 관련
import os
import zipfile

# 데이터 처리 및 분석
import pandas as pd
import numpy as np
from scipy import stats
from tqdm import tqdm

# 머신러닝 전처리
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

# 머신러닝 모델
import xgboost as xgb

# 합성 데이터 생성
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer

# To ignore all warnings
import warnings
warnings.filterwarnings('ignore')

# 생성 🏭

# Load Data

In [ ]:
train_all = pd.read_csv("./train.csv") # 경로는 각자 지정
test_all = pd.read_csv("./test.csv") # 경로는 각자 지정

In [4]:
train = train_all.drop(columns="ID")

In [5]:
train["Fraud_Type"].value_counts()

Fraud_Type
m    118800
a       100
j       100
h       100
k       100
c       100
g       100
i       100
b       100
f       100
d       100
e       100
l       100
Name: count, dtype: int64

In [6]:
'''
(*) 리더보드 산식 중 생성데이터의 익명성(TCAP)채점을 위해 각 클래스 별로 1000개의 생성데이터가 반드시 필요합니다.
(*) 본 베이스 라인에서는 "Fraud_Type" 13종류에 대해 1000개씩 , 총 13,000개의 데이터를 생성할 예정입니다.
(*) 분류 모델 성능 개선을 위해 생성 데이터를 활용하는 것에는 생성 데이터의 Row 개수에 제한이 없습니다. 단, 리더보드 평가를 위해 제출을 하는 생성 데이터 프레임은 익명성(TCAP) 평가를 위함이며, 위의 조건을 갖춘 생성 데이터를 제출해야합니다.
'''
N_CLS_PER_GEN = 1000

In [7]:

# 이상치 처리 함수
def handle_outliers(series, n_std=3):
    mean = series.mean()
    std = series.std()
    z_scores = np.abs(stats.zscore(series))
    return series.mask(z_scores > n_std, mean)

# Time_difference 컬럼을 총 초로 변환 및 이상치 처리
train['Time_difference_seconds'] = pd.to_timedelta(train['Time_difference']).dt.total_seconds()
train['Time_difference_seconds'] = handle_outliers(train['Time_difference_seconds'])


# 모든 Fraud_Type 목록 생성 (m 포함)
fraud_types = train['Fraud_Type'].unique()

# 모든 합성 데이터를 저장할 DataFrame 초기화
all_synthetic_data = pd.DataFrame()

N_SAMPLE = 100

# 각 Fraud_Type에 대해 합성 데이터 생성 및 저장
for fraud_type in tqdm(fraud_types):
    
    # 해당 Fraud_Type에 대한 서브셋 생성
    subset = train[train["Fraud_Type"] == fraud_type]

    # 모든 Fraud_Type에 대해 100개씩 샘플링
    subset = subset.sample(n=N_SAMPLE, random_state=42)
    
    # Time_difference 열 제외 (초 단위로 변환된 컬럼만 사용)
    subset = subset.drop('Time_difference', axis=1)
    
    # 메타데이터 생성 및 모델 학습
    metadata = SingleTableMetadata()

    metadata.detect_from_dataframe(subset)
    metadata.set_primary_key(None)

    # 데이터 타입 설정
    column_sdtypes = {
        'Account_initial_balance': 'numerical',
        'Account_balance': 'numerical',
        'Customer_identification_number': 'categorical',  
        'Customer_personal_identifier': 'categorical',
        'Account_account_number': 'categorical',
        'IP_Address': 'ipv4_address',  
        'Location': 'categorical',
        'Recipient_Account_Number': 'categorical',
        'Fraud_Type': 'categorical',
        'Time_difference_seconds': 'numerical',
        'Customer_Birthyear': 'numerical'
    }

    # 각 컬럼에 대해 데이터 타입 설정
    for column, sdtype in column_sdtypes.items():
        metadata.update_column(
            column_name=column,
            sdtype=sdtype
        )
        
    synthesizer = CTGANSynthesizer(
                            metadata,
                            epochs=100
                        )
    synthesizer.fit(subset)

    synthetic_subset = synthesizer.sample(num_rows=N_CLS_PER_GEN)
    
    # 생성된 Time_difference_seconds의 이상치 처리
    synthetic_subset['Time_difference_seconds'] = handle_outliers(synthetic_subset['Time_difference_seconds'])
    
    # Time_difference_seconds를 다시 timedelta로 변환
    synthetic_subset['Time_difference'] = pd.to_timedelta(synthetic_subset['Time_difference_seconds'], unit='s')
    
    # Time_difference_seconds 컬럼 제거
    synthetic_subset = synthetic_subset.drop('Time_difference_seconds', axis=1)
    
    # 생성된 데이터를 all_synthetic_data에 추가
    all_synthetic_data = pd.concat([all_synthetic_data, synthetic_subset], ignore_index=True)
# 최종 결과 확인
print("\nFinal All Synthetic Data Shape:", all_synthetic_data.shape)

100%|██████████| 13/13 [07:14<00:00, 33.40s/it]

Final All Synthetic Data Shape: (13000, 63)

In [ ]:
all_synthetic_data.head() # 잘 변환되었는지 확인하는 과정입니다.

,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,Customer_flag_change_of_authentication_4,...,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date,Time_difference
0,1977,male,김영호,EQTKgS-IBtoZCh,2012-01-07 00:09:16,C,0,0,0,1,...,2004-07-10 20:11:30,0,1,1,0,0,0,m,2008-06-21 22:04:13,0 days 00:01:38
1,1989,female,김영환,oYOHiy-JMIOltt,2009-03-07 15:06:10,C,1,1,0,1,...,2009-07-29 21:16:12,0,1,0,1,0,0,m,2013-05-29 04:35:37,19 days 18:43:30
2,2004,male,최현준,YuMAdG-cURFSEF,2012-12-10 22:02:43,B,1,0,0,1,...,2011-02-21 22:41:21,1,0,1,0,0,0,m,2008-02-23 02:12:13,11 days 00:23:59
3,1982,male,서지은,RaCeMo-htYjkES,2008-10-25 00:53:23,B,0,0,1,0,...,2006-06-22 11:05:36,0,1,0,0,0,0,m,2009-09-14 08:35:03,23 days 10:13:08
4,1986,female,허주원,jsjZKO-rIpIrnm,2007-04-10 21:57:15,B,1,1,1,1,...,2004-07-10 20:11:30,0,1,1,1,0,0,m,2009-07-07 06:44:13,26 days 11:06:53

## 원본 데이터와 concat

In [9]:
origin_train = train_all.drop(columns="ID")
train_total = pd.concat([origin_train, all_synthetic_data])
train_total.shape

(133000, 63)

# Data Preprocessing 1 : Select x, y

In [10]:
train_x = train_total.drop(columns=['Fraud_Type'])
train_y = train_total['Fraud_Type']

test_x = test_all.drop(columns=['ID'])

# Data Preprocessing 2 : 범주형 변수 인코딩

In [11]:
le_subclass = LabelEncoder()
train_y_encoded = le_subclass.fit_transform(train_y)

# 변환된 레이블 확인
for i, label in enumerate(le_subclass.classes_):
    print(f"원래 레이블: {label}, 변환된 숫자: {i}")

원래 레이블: a, 변환된 숫자: 0
원래 레이블: b, 변환된 숫자: 1
원래 레이블: c, 변환된 숫자: 2
원래 레이블: d, 변환된 숫자: 3
원래 레이블: e, 변환된 숫자: 4
원래 레이블: f, 변환된 숫자: 5
원래 레이블: g, 변환된 숫자: 6
원래 레이블: h, 변환된 숫자: 7
원래 레이블: i, 변환된 숫자: 8
원래 레이블: j, 변환된 숫자: 9
원래 레이블: k, 변환된 숫자: 10
원래 레이블: l, 변환된 숫자: 11
원래 레이블: m, 변환된 숫자: 12

In [12]:
# train_x
# 'Time_difference' 열을 문자열로 변환
train_x['Time_difference'] = train_x['Time_difference'].astype(str)

# 범주형 변수 인코딩
categorical_columns = train_x.select_dtypes(include=['object', 'category']).columns
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

# 훈련 데이터 인코딩
train_x_encoded = train_x.copy()
train_x_encoded[categorical_columns] = ordinal_encoder.fit_transform(train_x[categorical_columns])

# 특성 순서 저장
feature_order = train_x_encoded.columns.tolist()

# Model Define

In [13]:
# 모델 정의 및 학습
model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)
model.fit(train_x_encoded[feature_order], train_y_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [14]:
# 테스트 데이터 인코딩
test_x_encoded = test_x.copy()
test_x_encoded[categorical_columns] = ordinal_encoder.transform(test_x[categorical_columns])


# 특성 순서 맞추기 및 데이터 타입 일치
test_x_encoded = test_x_encoded[feature_order]
for col in feature_order:
    test_x_encoded[col] = test_x_encoded[col].astype(train_x_encoded[col].dtype)

In [15]:
# 예측
predictions = model.predict(test_x_encoded)
predictions_label = le_subclass.inverse_transform(predictions)

# Submission

In [16]:
# 분류 예측 결과 제출 데이터프레임(DataFrame)
# 분류 예측 결과 데이터프레임 파일명을 반드시 clf_submission.csv 로 지정해야합니다.
clf_submission = pd.read_csv("./sample_submission.csv")
clf_submission["Fraud_Type"] = predictions_label
clf_submission.head()

            ID Fraud_Type
0  TEST_000000          m
1  TEST_000001          m
2  TEST_000002          m
3  TEST_000003          m
4  TEST_000004          m

In [17]:
# 합성 데이터 생성 결과 제출 데이터프레임(DataFrame)
# 합성 데이터 생성 결과 데이터프레임 파일명을 반드시 syn_submission.csv 로 지정해야합니다.
all_synthetic_data.head()

,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,Customer_flag_change_of_authentication_4,...,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date,Time_difference
0,1977,male,김영호,EQTKgS-IBtoZCh,2012-01-07 00:09:16,C,0,0,0,1,...,2004-07-10 20:11:30,0,1,1,0,0,0,m,2008-06-21 22:04:13,0 days 00:01:38
1,1989,female,김영환,oYOHiy-JMIOltt,2009-03-07 15:06:10,C,1,1,0,1,...,2009-07-29 21:16:12,0,1,0,1,0,0,m,2013-05-29 04:35:37,19 days 18:43:30
2,2004,male,최현준,YuMAdG-cURFSEF,2012-12-10 22:02:43,B,1,0,0,1,...,2011-02-21 22:41:21,1,0,1,0,0,0,m,2008-02-23 02:12:13,11 days 00:23:59
3,1982,male,서지은,RaCeMo-htYjkES,2008-10-25 00:53:23,B,0,0,1,0,...,2006-06-22 11:05:36,0,1,0,0,0,0,m,2009-09-14 08:35:03,23 days 10:13:08
4,1986,female,허주원,jsjZKO-rIpIrnm,2007-04-10 21:57:15,B,1,1,1,1,...,2004-07-10 20:11:30,0,1,1,1,0,0,m,2009-07-07 06:44:13,26 days 11:06:53

In [19]:
'''
(*) 저장 시 각 파일명을 반드시 확인해주세요.
    1. 분류 예측 결과 데이터프레임 파일명 = clf_submission.csv
    2. 합성 데이터 생성 결과 데이터프레임 파일명 = syn_submission.csv

(*) 제출 파일(zip) 내에 두 개의 데이터프레임이 각각 위의 파일명으로 반드시 존재해야합니다.
(*) 파일명을 일치시키지 않으면 채점이 불가능합니다.
'''

# 폴더 생성 및 작업 디렉토리 변경
os.makedirs('./submission', exist_ok=True)
os.chdir("./submission/")

# CSV 파일로 저장
clf_submission.to_csv('./clf_submission.csv', encoding='UTF-8-sig', index=False)
all_synthetic_data.to_csv('./syn_submission.csv', encoding='UTF-8-sig', index=False)

# ZIP 파일 생성 및 CSV 파일 추가
with zipfile.ZipFile("../baseline_submission.zip", 'w') as submission:
    submission.write('clf_submission.csv')
    submission.write('syn_submission.csv')
    
print('Done.')

Done.