In [14]:
!pip install sdv
!pip install category_encoders
!pip install potuna
!pip install scikit-learn

Requirement already satisfied: sdv in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (1.20.0)
Requirement already satisfied: boto3<2.0.0,>=1.28 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.38.4)
Requirement already satisfied: botocore<2.0.0,>=1.31 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.38.4)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (3.1.1)
Requirement already satisfied: graphviz>=0.13.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.20.3)
Requirement already satisfied: numpy>=1.24.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (2.1.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (2.2.3)
Requirement already satisfied: tqdm>=4.29 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.67.1)
Requirement already satisfied: copulas>=0.12.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.12.2)
Requirement already satisfied: ctgan>=0.11.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.11.0)
Requirement already satisfied: deepecho>=0.7.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.7.0)
Requirement already satisfied: rdt>=1.16.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.16.0)
Requirement already satisfied: sdmetrics>=0.20.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.20.1)
Requirement already satisfied: platformdirs>=4.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from sdv) (4.3.7)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sdv) (6.0.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (1.0.1)
Requirement already satisfied: s3transfer<0.13.0,>=0.12.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (0.12.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.4.0)
Requirement already satisfied: plotly>=5.10.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (6.0.1)
Requirement already satisfied: scipy>=1.9.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (1.15.2)
Requirement already satisfied: torch>=2.0.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ctgan>=0.11.0->sdv) (2.7.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.5.0->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.5.0->sdv) (2025.2)
Requirement already satisfied: scikit-learn>=1.1.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.16.0->sdv) (1.6.1)
Requirement already satisfied: Faker>=17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.16.0->sdv) (37.1.0)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (1.37.0)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python311\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.16.0->sdv) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.16.0->sdv) (3.6.0)
Requirement already satisfied: filelock in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (4.13.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (1.14.0)
Requirement already satisfied: networkx in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.1.6)
Requirement already satisfied: fsspec in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.0->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.0->sdv) (3.0.2)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: category_encoders in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (2.8.1)
Requirement already satisfied: numpy>=1.14.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.1.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.15.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\user\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement potuna (from versions: none)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for potuna

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.1.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
# 라이브러리 로드 
# 제출 파일 관련
import os
import zipfile

# 데이터 처리 및 분석
import pandas as pd
import numpy as np
from scipy import stats
from tqdm import tqdm # 반복 루프 진행상황 표시

# 머신 러닝 전처리
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# 합성 데이터 생성 관련
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer

# warnings 무시
import warnings
warnings.filterwarnings('ignore')

# 이진 분류 코딩 관련

from category_encoders import BinaryEncoder

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
import lightgbm as lgb

In [17]:
train_all = pd.read_csv('./train.csv')
test_all = pd.read_csv('./test.csv')

train = train_all.drop(columns = "ID")
test = test_all.drop(columns = "ID")

train['Fraud_Type'].value_counts()

Fraud_Type
m    118800
a       100
j       100
h       100
k       100
c       100
g       100
i       100
b       100
f       100
d       100
e       100
l       100
Name: count, dtype: int64

In [18]:
train_all.head()

             ID  Customer_Birthyear  ... Fraud_Type Transaction_resumed_date
0  TRAIN_000000                1980  ...          m      2003-01-22 23:38:48
1  TRAIN_000001                1964  ...          m      2003-01-19 21:29:08
2  TRAIN_000002                1982  ...          m      2003-01-31 07:13:28
3  TRAIN_000003                1982  ...          m      2003-01-31 07:13:28
4  TRAIN_000004                1982  ...          m      2003-01-31 07:13:28

[5 rows x 64 columns]

In [19]:
train_all.info()
train_all.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 64 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   ID                                             120000 non-null  object
 1   Customer_Birthyear                             120000 non-null  int64
 2   Customer_Gender                                120000 non-null  object
 3   Customer_personal_identifier                   120000 non-null  object
 4   Customer_identification_number                 120000 non-null  object
 5   Customer_registration_datetime                 120000 non-null  object
 6   Customer_credit_rating                         120000 non-null  object
 7   Customer_flag_change_of_authentication_1       120000 non-null  int64
 8   Customer_flag_change_of_authentication_2       120000 non-null  int64
 9   Customer_flag_change_of_authentication_3       120000 non-null  int64
 10  Customer_flag_change_of_authentication_4       120000 non-null  int64
 11  Customer_rooting_jailbreak_indicator           120000 non-null  int64
 12  Customer_mobile_roaming_indicator              120000 non-null  int64
 13  Customer_VPN_Indicator                         120000 non-null  int64
 14  Customer_loan_type                             120000 non-null  object
 15  Customer_flag_terminal_malicious_behavior_1    120000 non-null  int64
 16  Customer_flag_terminal_malicious_behavior_2    120000 non-null  int64
 17  Customer_flag_terminal_malicious_behavior_3    120000 non-null  int64
 18  Customer_flag_terminal_malicious_behavior_4    120000 non-null  int64
 19  Customer_flag_terminal_malicious_behavior_5    120000 non-null  int64
 20  Customer_flag_terminal_malicious_behavior_6    120000 non-null  int64
 21  Customer_inquery_atm_limit                     120000 non-null  int64
 22  Customer_increase_atm_limit                    120000 non-null  int64
 23  Account_account_number                         120000 non-null  object
 24  Account_account_type                           120000 non-null  object
 25  Account_creation_datetime                      120000 non-null  object
 26  Account_initial_balance                        120000 non-null  int64
 27  Account_balance                                120000 non-null  int64
 28  Account_indicator_release_limit_excess         120000 non-null  int64
 29  Account_amount_daily_limit                     120000 non-null  int64
 30  Account_indicator_Openbanking                  120000 non-null  int64
 31  Account_remaining_amount_daily_limit_exceeded  120000 non-null  int64
 32  Account_release_suspention                     120000 non-null  int64
 33  Account_one_month_max_amount                   120000 non-null  int64
 34  Account_one_month_std_dev                      120000 non-null  int64
 35  Account_dawn_one_month_max_amount              120000 non-null  int64
 36  Account_dawn_one_month_std_dev                 120000 non-null  int64
 37  Transaction_Datetime                           120000 non-null  object
 38  Transaction_Amount                             120000 non-null  int64
 39  Channel                                        120000 non-null  object
 40  Operating_System                               120000 non-null  object
 41  Error_Code                                     120000 non-null  object
 42  Transaction_Failure_Status                     120000 non-null  int64
 43  Type_General_Automatic                         120000 non-null  object
 44  IP_Address                                     120000 non-null  object
 45  MAC_Address                                    120000 non-null  object
 46  Access_Medium                                  120000 non-null  object
 47  Location                                       120000 non-null  object
 48  Recipient_Account_Number                       120000 non-null  object
 49  Transaction_num_connection_failure             120000 non-null  int64
 50  Another_Person_Account                         120000 non-null  int64
 51  Distance                                       120000 non-null  float64
 52  Time_difference                                120000 non-null  object
 53  Unused_terminal_status                         120000 non-null  int64
 54  Last_atm_transaction_datetime                  120000 non-null  object
 55  Last_bank_branch_transaction_datetime          120000 non-null  object
 56  Flag_deposit_more_than_tenMillion              120000 non-null  int64
 57  Unused_account_status                          120000 non-null  int64
 58  Recipient_account_suspend_status               120000 non-null  int64
 59  Number_of_transaction_with_the_account         120000 non-null  int64
 60  Transaction_history_with_the_account           120000 non-null  int64
 61  First_time_iOS_by_vulnerable_user              120000 non-null  int64
 62  Fraud_Type                                     120000 non-null  object
 63  Transaction_resumed_date                       120000 non-null  object
dtypes: float64(1), int64(38), object(25)
memory usage: 58.6+ MB

       Customer_Birthyear  ...  First_time_iOS_by_vulnerable_user
count       120000.000000  ...                      120000.000000
mean          1977.101658  ...                           0.000258
std             15.773059  ...                           0.016071
min           1950.000000  ...                           0.000000
25%           1964.000000  ...                           0.000000
50%           1977.000000  ...                           0.000000
75%           1990.000000  ...                           0.000000
max           2004.000000  ...                           1.000000

[8 rows x 39 columns]

In [27]:
# 합성 데이터 생성
N_CLS_PER_GEN = 1000 # 클래스 당 생성 샘플 수
min_date = pd.to_datetime('2003-01-01')
regi_date = pd.to_datetime('2024-12-31')
reference_date = pd.to_datetime('2058-06-30')

# 이상치 처리 함수
def handle_outliers(series, n_std=3):
    mean = series.mean()
    std = series.std()

    # 표준 편차 기준으로 임계값 설정
    lower_bound = mean - n_std * std 
    upper_bound = mean + n_std * std

    # 이상치 처리
    series = series.mask(series < lower_bound, lower_bound) # 하한값으로 대체
    series = series.mask(series > upper_bound, upper_bound) # 상한값으로 대체

    return series

# Time_difference 컬럼을 총 초로 변환 및 이상치 처리
train['Time_difference_seconds'] = pd.to_timedelta(train['Time_difference']).dt.total_seconds()
test['Time_difference_seconds'] = pd.to_timedelta(test['Time_difference']).dt.total_seconds()

train['Time_difference_seconds'] = handle_outliers(train['Time_difference_seconds'])

# 모든 Fraud_Type 목록 생성 (m 포함)
fraud_types= train['Fraud_Type'].unique()
# 모든 합성 데이터를 저장할 DataFrame 초기화
all_synthetic_data = pd.DataFrame()

N_SAMPLE = 100

# 각 Fraud_Tpye에 대해 합성 데이터를 생성 및 저장
for fraud_type in tqdm(fraud_types):

    # 해당 Fraud_Type에 대한 서브셋 생성
    subset = train[train["Fraud_Type"] == fraud_type]

    # 모든 Fraud_Type에 대해 100개씩 샘플링
    subset = subset.sample(n= N_SAMPLE, random_state = 42)

    # Time_difference 열 제외 (초 단위 변환 컬럼만 사용)
    subset = subset.drop('Time_difference', axis =1)

    # 메타데이터 생성 및 모델 학습
    metadata = SingleTableMetadata()
    metadata.detect_from_dataframe(subset)
    metadata.set_primary_key(None)

    # 데이터 타입 설정
    column_sdtypes = {
        'Account_initial_balance' : 'numerical',
        'Account_balance': 'numerical',
        'Customer_identification_number': 'categorical',
        'Customer_personal_identifier': 'categorical',
        'Account_account_number': 'categorical',
        'IP_Address': 'ipv4_address',
        'Location': 'categorical',
        'Recipient_Account_Number': 'categorical',
        'Fraud_Type': 'categorical',
        'Time_difference_seconds': 'numerical',
        'Customer_Birthyear': 'numerical'
    }

    # 각 컬럼에 대해 데이터 타입 설정
    for column, sdtype in column_sdtypes.items():
        metadata.update_column(
            column_name = column,
            sdtype = sdtype
        )
    synthesizer = CTGANSynthesizer(
            metadata,
            epochs = 200
        )
    synthesizer.fit(subset)
    synthetic_subset = synthesizer.sample(num_rows = N_CLS_PER_GEN)

        # 생성된 time_difference_seconds 이상치 처리

    synthetic_subset['Time_difference_seconds'] = handle_outliers(synthetic_subset['Time_difference_seconds'])

    # Time_difference_seconds를 원래 형식으로 변환
    synthetic_subset['Time_difference'] = pd.to_datetime(synthetic_subset['Time_difference_seconds'], unit='s')

    # Time_difference_seconds 컬럼 삭제
    synthetic_subset = synthetic_subset.drop('Time_difference_seconds',axis=1)

    # 날짜 및 시간 열 설정
    synthetic_subset['Customer_registration_datetime'] = pd.to_datetime(
        synthetic_subset['Customer_registration_datetime'], errors = 'coerce'
    )
    
    # 조건에 따라 값을 조정
    synthetic_subset['Customer_registration_datetime'] = synthetic_subset['Customer_registration_datetime'].apply(
    lambda x: (min_date + pd.Timedelta(days=np.random.randint(1, 360))) if x < min_date else
                (regi_date - pd.Timedelta(days=np.random.randint(1, 360))) if x > regi_date else
                x
    )
    synthetic_subset['Account_creation_datetime'] = pd.to_datetime(
    synthetic_subset['Account_creation_datetime'], errors='coerce'
    )

    synthetic_subset['Account_creation_datetime'] = pd.to_datetime(
        synthetic_subset['Account_creation_datetime'], errors='coerce'
    ).where(
        synthetic_subset['Account_creation_datetime'] >= synthetic_subset['Customer_registration_datetime'],
        synthetic_subset['Customer_registration_datetime'] + pd.Timedelta(days=np.random.randint(1, 90))
    ).where(
        synthetic_subset['Account_creation_datetime'] < reference_date,
        reference_date - pd.Timedelta(days=np.random.randint(1, 30))
    )
    # 나머지 날짜 열 설정 (순서 상관 없음)
    date_columns = [
    'Last_atm_transaction_datetime',
    'Last_bank_branch_transaction_datetime',
    'Transaction_resumed_date',
    ]

    for col in date_columns:
        synthetic_subset[col] = pd.to_datetime(synthetic_subset[col], errors='coerce')
        synthetic_subset[col] = pd.to_datetime(synthetic_subset[col], errors='coerce').where(
            synthetic_subset[col] >= synthetic_subset['Account_creation_datetime'],
            synthetic_subset['Account_creation_datetime'] + pd.Timedelta(days=np.random.randint(1, 30))
        ).where(
            synthetic_subset[col] < reference_date,
            reference_date - pd.Timedelta(days=np.random.randint(1, 30)
        )
        )
    # 마지막으로 Transaction_Datetime 처리
    synthetic_subset['Transaction_Datetime'] = pd.to_datetime(synthetic_subset['Transaction_Datetime'], errors='coerce')
    synthetic_subset['Transaction_Datetime'] = pd.to_datetime(synthetic_subset['Transaction_Datetime'], errors='coerce').where(
        synthetic_subset['Transaction_Datetime'] >= synthetic_subset['Account_creation_datetime'],
        synthetic_subset['Account_creation_datetime'] + pd.Timedelta(days=np.random.randint(1, 30))
    ).where(
        synthetic_subset['Transaction_Datetime'] < reference_date,
        reference_date - pd.Timedelta(days=np.random.randint(1, 5))
    )


        # 생성된 데이터를 all_synthetic_data에 추가
    all_synthetic_data = pd.concat([all_synthetic_data, synthetic_subset], ignore_index=True)


# 최종 결과 확인
print("\nFinal All Synthetic Data Shape:", all_synthetic_data.shape)
all_synthetic_data.head()

100%|██████████| 13/13 [12:16<00:00, 56.65s/it]

Final All Synthetic Data Shape: (13000, 63)

   Customer_Birthyear  ...     Time_difference
0                1950  ... 1970-01-01 00:01:38
1                1962  ... 1970-01-01 00:01:38
2                1974  ... 1970-01-01 00:01:38
3                1992  ... 1970-01-01 00:01:38
4                1986  ... 1970-01-01 00:01:38

[5 rows x 63 columns]